### PR TITLE
adds svs into portfolio section

### PR DESCRIPTION
**Pull request by bmordan**
screen shot 2015-06-23 at 17 26 17
screen shot 2015-06-23 at 17 26 28

### CODE REVIEW

**Comment by alanshaw** [comment]
I think the colour should be the SVS orange and we should link to the sites.

**Comment by bmordan** [comment]
Adds Sam Labs
screen shot 2015-06-23 at 17 43 53
screen shot 2015-06-23 at 17 44 06

**Comment by bmordan** [comment]
screen shot 2015-06-24 at 16 12 33

**Comment by bmordan** [comment]
Actually I prefer the light text
screen shot 2015-06-24 at 16 14 01

**Comment by olizilla** [comment]
:+1:

**Pull request merged**
